In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/ai_job_dataset.csv')

In [3]:
df.head()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
0,AI00001,AI Research Scientist,90376,USD,SE,CT,China,M,China,50,"Tableau, PyTorch, Kubernetes, Linux, NLP",Bachelor,9,Automotive,2024-10-18,2024-11-07,1076,5.9,Smart Analytics
1,AI00002,AI Software Engineer,61895,USD,EN,CT,Canada,M,Ireland,100,"Deep Learning, AWS, Mathematics, Python, Docker",Master,1,Media,2024-11-20,2025-01-11,1268,5.2,TechCorp Inc
2,AI00003,AI Specialist,152626,USD,MI,FL,Switzerland,L,South Korea,0,"Kubernetes, Deep Learning, Java, Hadoop, NLP",Associate,2,Education,2025-03-18,2025-04-07,1974,9.4,Autonomous Tech
3,AI00004,NLP Engineer,80215,USD,SE,FL,India,M,India,50,"Scala, SQL, Linux, Python",PhD,7,Consulting,2024-12-23,2025-02-24,1345,8.6,Future Systems
4,AI00005,AI Consultant,54624,EUR,EN,PT,France,S,Singapore,100,"MLOps, Java, Tableau, Python",Master,0,Media,2025-04-15,2025-06-23,1989,6.6,Advanced Robotics

In [4]:
df.tail()

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
14995,AI14996,Robotics Engineer,38604,USD,EN,FL,Finland,S,Finland,50,"Java, Kubernetes, Azure",Bachelor,1,Energy,2025-02-06,2025-03-25,1635,7.9,Advanced Robotics
14996,AI14997,Machine Learning Researcher,57811,GBP,EN,CT,United Kingdom,M,United Kingdom,0,"Mathematics, Docker, SQL, Deep Learning",Master,0,Government,2024-10-16,2024-10-30,1624,8.2,Smart Analytics
14997,AI14998,NLP Engineer,189490,USD,EX,CT,South Korea,L,South Korea,50,"Scala, Spark, NLP",Associate,17,Manufacturing,2024-03-19,2024-05-02,1336,7.4,AI Innovations
14998,AI14999,Head of AI,79461,EUR,EN,FT,Netherlands,M,Netherlands,0,"Java, Computer Vision, Python, TensorFlow",PhD,1,Real Estate,2024-03-22,2024-04-23,1935,5.6,Smart Analytics
14999,AI15000,Computer Vision Engineer,56481,USD,MI,PT,Austria,S,Austria,50,"Scala, Azure, Deep Learning, GCP, Mathematics",PhD,2,Technology,2024-07-18,2024-08-10,2492,7.6,AI Innovations

In [5]:
df.sample(5)

,job_id,job_title,salary_usd,salary_currency,experience_level,employment_type,company_location,company_size,employee_residence,remote_ratio,required_skills,education_required,years_experience,industry,posting_date,application_deadline,job_description_length,benefits_score,company_name
7535,AI07536,AI Product Manager,95821,USD,EX,CT,Austria,S,Austria,100,"Data Visualization, Computer Vision, Deep Lear...",Associate,18,Technology,2024-02-21,2024-04-17,1103,5.5,Digital Transformation LLC
11064,AI11065,Data Scientist,69872,USD,MI,FT,India,L,India,100,"GCP, Hadoop, MLOps",PhD,3,Healthcare,2024-03-13,2024-04-25,1941,5.8,AI Innovations
6641,AI06642,Machine Learning Engineer,135754,USD,EX,PT,Australia,S,Netherlands,0,"Python, SQL, Tableau, TensorFlow",Master,16,Gaming,2025-01-29,2025-04-01,1291,5.3,Machine Intelligence Group
6098,AI06099,Data Engineer,96832,USD,SE,CT,Japan,S,Japan,100,"Java, TensorFlow, Linux",Associate,8,Gaming,2024-05-27,2024-07-24,797,8.1,Cognitive Computing
13780,AI13781,Deep Learning Engineer,149377,USD,SE,CT,Sweden,M,Sweden,100,"PyTorch, NLP, Kubernetes",PhD,7,Energy,2024-07-24,2024-09-07,524,7.1,Quantum Computing Inc

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   job_id                  15000 non-null  object
 1   job_title               15000 non-null  object
 2   salary_usd              15000 non-null  int64
 3   salary_currency         15000 non-null  object
 4   experience_level        15000 non-null  object
 5   employment_type         15000 non-null  object
 6   company_location        15000 non-null  object
 7   company_size            15000 non-null  object
 8   employee_residence      15000 non-null  object
 9   remote_ratio            15000 non-null  int64
 10  required_skills         15000 non-null  object
 11  education_required      15000 non-null  object
 12  years_experience        15000 non-null  int64
 13  industry                15000 non-null  object
 14  posting_date            15000 non-null  object
 15  application_deadline    15000 non-null  object
 16  job_description_length  15000 non-null  int64
 17  benefits_score          15000 non-null  float64
 18  company_name            15000 non-null  object
dtypes: float64(1), int64(4), object(14)
memory usage: 2.2+ MB

In [8]:
df.shape

(15000, 19)